export enum PlaneErrorCode {
  INVALID_CONFIG = 'INVALID_CONFIG',
  NOT_SIGNED_IN = 'NOT_SIGNED_IN',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  HTTP_ERROR = 'HTTP_ERROR',
  UNEXPECTED_RESPONSE = 'UNEXPECTED_RESPONSE',
  NOT_FOUND = 'NOT_FOUND',
  RATE_LIMITED = 'RATE_LIMITED',
}
